/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "helios";
const char* rss_saver_options =
    "  -ions         <1..30000>\n"
    "  -size         <1..100>\n"
    "  -emitters     <1..10>\n"
    "  -attracters   <1..10>\n"
    "  -speed        <1..100>\n"
    "  -cameraspeed  <0..100>\n"
    "  -surface      <0..1>\n"
    "  -blur         <0..100>\n"
    ;

/* ---- live-option runtime (web settings panel; see shell.html) ---- */
#include <string.h>

extern int dAttracters;
extern int dBlur;
extern int dCameraspeed;
extern int dEmitters;
extern int dIons;
extern int dSize;
extern int dSpeed;
extern int dSurface;

static struct { const char* name; int* addr; } rss_opt_addrs[] = {
    { "ions", &dIons },
    { "size", &dSize },
    { "emitters", &dEmitters },
    { "attracters", &dAttracters },
    { "speed", &dSpeed },
    { "cameraspeed", &dCameraspeed },
    { "surface", &dSurface },
    { "blur", &dBlur },
};

extern "C" int rss_set_option(const char* name, int value) {
    for (unsigned i = 0; i < sizeof(rss_opt_addrs)/sizeof(rss_opt_addrs[0]); ++i) {
        if (!strcmp(rss_opt_addrs[i].name, name)) {
            *rss_opt_addrs[i].addr = value;
            return 1;
        }
    }
    return 0;
}

extern void initSaver();
extern void cleanUp();
extern "C" void rss_restart(void) { cleanUp(); initSaver(); }
