/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "helios";
const char* rss_saver_options =
    "  -ions         <1..30000>\n"
    "  -size         <1..100>\n"
    "  -emitters     <1..10>\n"
    "  -attracters   <1..10>\n"
    "  -speed        <1..100>\n"
    "  -cameraspeed  <0..100>\n"
    "  -surface      <0..1>\n"
    "  -blur         <0..100>\n"
    ;
