/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "hyperspace";
const char* rss_saver_options =
    "  -speed       <1..100>\n"
    "  -stars       <0..10000>\n"
    "  -starsize    <1..100>\n"
    "  -resolution  <4..20>\n"
    "  -depth       <1..10>\n"
    "  -fov         <10..150>\n"
    "  -usetunnels  <0..1>\n"
    "  -usegoo      <0..1>\n"
    "  -shaders     <0..1>\n"
    ;

/* ---- live-option runtime (web settings panel; see shell.html) ---- */
#include <string.h>

extern int dDepth;
extern int dFov;
extern int dResolution;
extern int dShaders;
extern int dSpeed;
extern int dStarSize;
extern int dStars;
extern int dUseGoo;
extern int dUseTunnels;

static struct { const char* name; int* addr; } rss_opt_addrs[] = {
    { "speed", &dSpeed },
    { "stars", &dStars },
    { "starsize", &dStarSize },
    { "resolution", &dResolution },
    { "depth", &dDepth },
    { "fov", &dFov },
    { "usetunnels", &dUseTunnels },
    { "usegoo", &dUseGoo },
    { "shaders", &dShaders },
};

extern "C" int rss_set_option(const char* name, int value) {
    for (unsigned i = 0; i < sizeof(rss_opt_addrs)/sizeof(rss_opt_addrs[0]); ++i) {
        if (!strcmp(rss_opt_addrs[i].name, name)) {
            *rss_opt_addrs[i].addr = value;
            return 1;
        }
    }
    return 0;
}

extern void initSaver();
extern void cleanUp();
extern "C" void rss_restart(void) { cleanUp(); initSaver(); }
