/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "hyperspace";
const char* rss_saver_options =
    "  -speed       <1..100>\n"
    "  -stars       <0..10000>\n"
    "  -starsize    <1..100>\n"
    "  -resolution  <4..20>\n"
    "  -depth       <1..10>\n"
    "  -fov         <10..150>\n"
    "  -usetunnels  <0..1>\n"
    "  -usegoo      <0..1>\n"
    "  -shaders     <0..1>\n"
    ;
