/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "flux";
const char* rss_saver_options =
    "  -default      <1..6>  (presets)\n"
    "  -fluxes       <1..100>\n"
    "  -particles    <1..1000>\n"
    "  -trail        <3..10000>\n"
    "  -geometry     <0..2>\n"
    "  -size         <1..100>\n"
    "  -complexity   <1..10>\n"
    "  -randomize    <0..100>\n"
    "  -expansion    <0..100>\n"
    "  -rotation     <1..100>\n"
    "  -wind         <1..10>\n"
    "  -instability  <1..100>\n"
    "  -blur         <0..100>\n"
    ;
