/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "solarwinds";
const char* rss_saver_options =
    "  -winds          <1..10>\n"
    "  -emitters       <1..1000>\n"
    "  -perticles      <1..10000>\n"
    "  -geometry       <0..2>\n"
    "  -size           <1..100>\n"
    "  -windspeed      <1..100>\n"
    "  -emitterspeed   <1..100>\n"
    "  -particlespeed  <1..100>\n"
    "  -blur           <1..100>\n"
    ;
