/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "skyrocket";
const char* rss_saver_options =
    "  -maxrockets      <1..100>\n"
    "  -smoke           <0..40>\n"
    "  -explosionsmoke  <0..5>\n"
    "  -wind            <0..100>\n"
    "  -ambient         <0..100>\n"
    "  -stardensity     <0..100>\n"
    "  -flare           <0..100>\n"
    "  -moonglow        <0..100>\n"
    "  -sound           <0..100>\n"
    "  -moon            <0..1>\n"
    "  -clouds          <0..1>\n"
    "  -earth           <0..1>\n"
    "  -illumination    <0..1>\n"
    ;

/* ---- live-option runtime (web settings panel; see shell.html) ---- */
#include <string.h>

extern int dAmbient;
extern int dClouds;
extern int dEarth;
extern int dExplosionsmoke;
extern int dFlare;
extern int dIllumination;
extern int dMaxrockets;
extern int dMoon;
extern int dMoonglow;
extern int dSmoke;
extern int dSound;
extern int dStardensity;
extern int dWind;

static struct { const char* name; int* addr; } rss_opt_addrs[] = {
    { "maxrockets", &dMaxrockets },
    { "smoke", &dSmoke },
    { "explosionsmoke", &dExplosionsmoke },
    { "wind", &dWind },
    { "ambient", &dAmbient },
    { "stardensity", &dStardensity },
    { "flare", &dFlare },
    { "moonglow", &dMoonglow },
    { "sound", &dSound },
    { "moon", &dMoon },
    { "clouds", &dClouds },
    { "earth", &dEarth },
    { "illumination", &dIllumination },
};

extern "C" int rss_set_option(const char* name, int value) {
    for (unsigned i = 0; i < sizeof(rss_opt_addrs)/sizeof(rss_opt_addrs[0]); ++i) {
        if (!strcmp(rss_opt_addrs[i].name, name)) {
            *rss_opt_addrs[i].addr = value;
            return 1;
        }
    }
    return 0;
}

extern void initSaver();
extern void cleanUp();
extern "C" void rss_restart(void) { cleanUp(); initSaver(); }
