/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "skyrocket";
const char* rss_saver_options =
    "  -maxrockets      <1..100>\n"
    "  -smoke           <0..40>\n"
    "  -explosionsmoke  <0..5>\n"
    "  -wind            <0..100>\n"
    "  -ambient         <0..100>\n"
    "  -stardensity     <0..100>\n"
    "  -flare           <0..100>\n"
    "  -moonglow        <0..100>\n"
    "  -sound           <0..100>\n"
    "  -moon            <0..1>\n"
    "  -clouds          <0..1>\n"
    "  -earth           <0..1>\n"
    "  -illumination    <0..1>\n"
    ;
