LIBNAME = rsmath
LIB_SRC = $(wildcard src/rsMath/*.cpp) $(wildcard src/Rgbhsl/*.cpp) \
          $(wildcard src/rsText/*.cpp) $(wildcard src/Implicit/*.cpp) $(wildcard src/util/*.cpp)
LIB_IS_SAVER_CODE = yes
LIB_CFLAGS = -Isrc $(GL4ES_INC) $(GLUES_INC)
include ../../makefiles/make_lib.mk
