/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "flocks";
const char* rss_saver_options =
    "  -leaders         <1..100>\n"
    "  -followers       <0..10000>\n"
    "  -geometry        <0..1>\n"
    "  -size            <1..100>\n"
    "  -complexity      <1..10>\n"
    "  -speed           <1..100>\n"
    "  -stretch         <0..100>\n"
    "  -colorfadespeed  <0..100>\n"
    "  -fadespeed       <0..100>\n"
    "  -chromatek       <0..1>\n"
    "  -connections     <0..1>\n"
    ;

/* ---- live-option runtime (web settings panel; see shell.html) ---- */
#include <string.h>

extern int dChromatek;
extern int dColorfadespeed;
extern int dComplexity;
extern int dConnections;
extern int dFollowers;
extern int dGeometry;
extern int dLeaders;
extern int dSize;
extern int dSpeed;
extern int dStretch;

static struct { const char* name; int* addr; } rss_opt_addrs[] = {
    { "leaders", &dLeaders },
    { "followers", &dFollowers },
    { "geometry", &dGeometry },
    { "size", &dSize },
    { "complexity", &dComplexity },
    { "speed", &dSpeed },
    { "stretch", &dStretch },
    { "colorfadespeed", &dColorfadespeed },
    { "fadespeed", &dColorfadespeed },
    { "chromatek", &dChromatek },
    { "connections", &dConnections },
};

extern "C" int rss_set_option(const char* name, int value) {
    for (unsigned i = 0; i < sizeof(rss_opt_addrs)/sizeof(rss_opt_addrs[0]); ++i) {
        if (!strcmp(rss_opt_addrs[i].name, name)) {
            *rss_opt_addrs[i].addr = value;
            return 1;
        }
    }
    return 0;
}

extern void initSaver();
extern void cleanUp();
extern "C" void rss_restart(void) { cleanUp(); initSaver(); }
