/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "flocks";
const char* rss_saver_options =
    "  -leaders         <1..100>\n"
    "  -followers       <0..10000>\n"
    "  -geometry        <0..1>\n"
    "  -size            <1..100>\n"
    "  -complexity      <1..10>\n"
    "  -speed           <1..100>\n"
    "  -stretch         <0..100>\n"
    "  -colorfadespeed  <0..100>\n"
    "  -fadespeed       <0..100>\n"
    "  -chromatek       <0..1>\n"
    "  -connections     <0..1>\n"
    ;
