/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "fieldlines";
const char* rss_saver_options =
    "  -ions        <1..50>\n"
    "  -stepsize    <1..100>\n"
    "  -maxsteps    <1..10000>\n"
    "  -width       <1..100>\n"
    "  -speed       <1..100>\n"
    "  -constwidth  <0..1>\n"
    "  -electric    <0..1>\n"
    ;
