/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "fieldlines";
const char* rss_saver_options =
    "  -ions        <1..50>\n"
    "  -stepsize    <1..100>\n"
    "  -maxsteps    <1..10000>\n"
    "  -width       <1..100>\n"
    "  -speed       <1..100>\n"
    "  -constwidth  <0..1>\n"
    "  -electric    <0..1>\n"
    ;

/* ---- live-option runtime (web settings panel; see shell.html) ---- */
#include <string.h>

extern int dConstwidth;
extern int dElectric;
extern int dIons;
extern int dMaxSteps;
extern int dSpeed;
extern int dStepSize;
extern int dWidth;

static struct { const char* name; int* addr; } rss_opt_addrs[] = {
    { "ions", &dIons },
    { "stepsize", &dStepSize },
    { "maxsteps", &dMaxSteps },
    { "width", &dWidth },
    { "speed", &dSpeed },
    { "constwidth", &dConstwidth },
    { "electric", &dElectric },
};

extern "C" int rss_set_option(const char* name, int value) {
    for (unsigned i = 0; i < sizeof(rss_opt_addrs)/sizeof(rss_opt_addrs[0]); ++i) {
        if (!strcmp(rss_opt_addrs[i].name, name)) {
            *rss_opt_addrs[i].addr = value;
            return 1;
        }
    }
    return 0;
}

extern void initSaver();
extern void cleanUp();
extern "C" void rss_restart(void) { cleanUp(); initSaver(); }
