/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "plasma";
const char* rss_saver_options =
    "  -zoom        <1..100>\n"
    "  -focus       <1..100>\n"
    "  -speed       <1..100>\n"
    "  -resolution  <1..100>\n"
    ;

/* ---- live-option runtime (web settings panel; see shell.html) ---- */
#include <string.h>

extern int dFocus;
extern int dResolution;
extern int dSpeed;
extern int dZoom;

static struct { const char* name; int* addr; } rss_opt_addrs[] = {
    { "zoom", &dZoom },
    { "focus", &dFocus },
    { "speed", &dSpeed },
    { "resolution", &dResolution },
};

extern "C" int rss_set_option(const char* name, int value) {
    for (unsigned i = 0; i < sizeof(rss_opt_addrs)/sizeof(rss_opt_addrs[0]); ++i) {
        if (!strcmp(rss_opt_addrs[i].name, name)) {
            *rss_opt_addrs[i].addr = value;
            return 1;
        }
    }
    return 0;
}

extern void initSaver();
extern void cleanUp();
extern "C" void rss_restart(void) { cleanUp(); initSaver(); }
