/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "plasma";
const char* rss_saver_options =
    "  -zoom        <1..100>\n"
    "  -focus       <1..100>\n"
    "  -speed       <1..100>\n"
    "  -resolution  <1..100>\n"
    ;
