#!/usr/bin/env python3
"""gen_help.py - generate per-saver rss_help.cpp from handleCommandLine().

Each RSS saver lists its options as getArgumentsValue(argc, argv, "-name",
var, min, max) calls inside handleCommandLine(). This script parses those calls
and emits a small rss_help.cpp defining:

    const char* rss_saver_name    = "<saver>";
    const char* rss_saver_options = "  -name   <min..max>\n ...";

which the SDL shell (libs/librs) prints on --help. Savers with no options get
an empty table. Re-run after editing a saver's handleCommandLine.

Usage: gen_help.py savers/<name>/<name>.cpp [savers/<name2>/...]
       gen_help.py --all          (process every savers/*/ with a .cpp)
"""
import re
import sys
import os

# getArgumentsValue(argc, argv, std::string("-foo"), var, MIN, MAX)
#   capture: option name, and optional min, max (numeric or identifier)
CALL_RE = re.compile(
    r'getArgumentsValue\s*\(\s*argc\s*,\s*argv\s*,\s*'
    r'std::string\(\s*"(-[A-Za-z0-9_]+)"\s*\)\s*,\s*'
    r'[A-Za-z_][A-Za-z0-9_]*\s*'
    r'(?:,\s*([A-Za-z0-9_]+)\s*,\s*([A-Za-z0-9_]+)\s*)?\)'
)

def parse_options(cpp_path):
    src = open(cpp_path, encoding='utf-8', errors='replace').read()
    # isolate the RS_XSCREENSAVER handleCommandLine body if present
    m = re.search(r'void\s+handleCommandLine\s*\([^)]*\)\s*\{', src)
    body = src[m.end():] if m else src
    # cut at the matching-ish end (next top-level function) - good enough:
    end = body.find('\n}\n')
    if end != -1:
        body = body[:end]
    opts = []
    seen = set()
    for mo in CALL_RE.finditer(body):
        name, lo, hi = mo.group(1), mo.group(2), mo.group(3)
        if name in seen:
            continue
        seen.add(name)
        opts.append((name, lo, hi))
    return opts

def c_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def emit(saver, opts, out_path):
    lines = []
    if opts:
        width = max(len(n) for n, _, _ in opts)
        for name, lo, hi in opts:
            rng = ''
            if lo is not None and hi is not None:
                # DEFAULTSn presets are sequential ints; show as 1..N.
                dlo = re.match(r'DEFAULTS(\d+)', lo or '')
                dhi = re.match(r'DEFAULTS(\d+)', hi or '')
                if dlo and dhi:
                    rng = '<%s..%s>  (presets)' % (dlo.group(1), dhi.group(1))
                else:
                    rng = '<%s..%s>' % (lo, hi)
            lines.append('  %-*s  %s' % (width, name, rng))
    table = '\n'.join(lines)
    body = (
        '/* AUTO-GENERATED by scripts/gen_help.py - do not edit.\n'
        ' * Per-saver option table for the SDL shell\'s --help. */\n\n'
        'extern const char* rss_saver_name;\n'
        'extern const char* rss_saver_options;\n\n'
        'const char* rss_saver_name = "%s";\n' % c_escape(saver)
    )
    if table:
        body += 'const char* rss_saver_options =\n'
        for ln in table.split('\n'):
            body += '    "%s\\n"\n' % c_escape(ln)
        body += '    ;\n'
    else:
        body += 'const char* rss_saver_options = "";\n'
    open(out_path, 'w').write(body)
    return len(opts)

def find_main_cpp(saver_dir):
    """The saver's main source. Usually <dir>.cpp, but solarwinds uses
    solarWinds.cpp (case differs), so match case-insensitively, preferring a
    file that actually defines handleCommandLine."""
    name = os.path.basename(saver_dir.rstrip('/'))
    cands = [f for f in os.listdir(saver_dir)
             if f.endswith('.cpp') and f != 'rss_help.cpp']
    for f in cands:
        if f[:-4].lower() == name.lower():
            return os.path.join(saver_dir, f)
    for f in cands:
        p = os.path.join(saver_dir, f)
        if 'handleCommandLine' in open(p, errors='replace').read():
            return p
    return None

def process(cpp_path):
    saver = os.path.basename(os.path.dirname(cpp_path))
    opts = parse_options(cpp_path)
    out = os.path.join(os.path.dirname(cpp_path), 'rss_help.cpp')
    n = emit(saver, opts, out)
    print('%-14s %2d options -> %s' % (saver, n, out))

def main(argv):
    if not argv:
        print(__doc__); return 1
    if argv[0] == '--all':
        root = os.path.join(os.path.dirname(__file__), '..', 'savers')
        for d in sorted(os.listdir(root)):
            sd = os.path.join(root, d)
            if not os.path.isdir(sd):
                continue
            cpp = find_main_cpp(sd)
            if cpp:
                process(cpp)
        return 0
    for p in argv:
        process(p)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
