/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "euphoria";
const char* rss_saver_options =
    "  -default        <1..9>  (presets)\n"
    "  -wisps          <0..100>\n"
    "  -background     <0..100>\n"
    "  -density        <1..100>\n"
    "  -visibility     <1..100>\n"
    "  -speed          <1..100>\n"
    "  -feedback       <0..100>\n"
    "  -feedbackspeed  <1..100>\n"
    "  -feedbacksize   <FEEDBACKSIZE_MIN..FEEDBACKSIZE_MAX>\n"
    "  -wireframe      <0..1>\n"
    "  -texture        <0..4>\n"
    ;
