/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "cyclone";
const char* rss_saver_options =
    "  -cyclones    <1..10>\n"
    "  -particles   <1..10000>\n"
    "  -size        <1..100>\n"
    "  -complexity  <1..10>\n"
    "  -speed       <1..100>\n"
    "  -stretch     <0..1>\n"
    "  -showcurves  <0..1>\n"
    ;
