/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "microcosm";
const char* rss_saver_options =
    "  -stime        <0..300>\n"
    "  -ktime        <0..300>\n"
    "  -background   <0..100>\n"
    "  -resolution   <20..100>\n"
    "  -depth        <1..10>\n"
    "  -gizmospeed   <1..100>\n"
    "  -colorspeed   <1..100>\n"
    "  -cameraspeed  <1..100>\n"
    "  -shaders      <0..1>\n"
    "  -fog          <0..1>\n"
    ;
