/* AUTO-GENERATED by scripts/gen_help.py - do not edit.
 * Per-saver option table for the SDL shell's --help. */

extern const char* rss_saver_name;
extern const char* rss_saver_options;

const char* rss_saver_name = "lattice";
const char* rss_saver_options =
    "  -default         <1..9>  (presets)\n"
    "  -longitude       <3..100>\n"
    "  -latitude        <3..100>\n"
    "  -thickness       <1..100>\n"
    "  -density         <1..100>\n"
    "  -depth           <1..10>\n"
    "  -fov             <30..150>\n"
    "  -pathrandomness  <0..10>\n"
    "  -speed           <1..100>\n"
    "  -texture         <0..9>\n"
    "  -smooth          <0..1>\n"
    "  -fog             <0..1>\n"
    ;
